spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: cloud-service-good
eureka:
  client:
    service-url:
      defaultZoone: http://localhost:8761/eureka/
server:
  port: 7010